// Most commonly used kanji in Japanese
//
// The romaji array includes common on'yomi (Chinese-derived) and
// kun'yomi (native Japanese) readings. Not all possible readings are
// listed, only the most frequent ones.
//
// Generated by Grok 3, not checked for correctness yet.

const kanji = [
  {
    kanji: "日",
    romaji: [
      { type: "on'yomi", value: "nichi" },
      { type: "kun'yomi", value: "hi" },
    ],
    english: ["day", "sun", "Japan"],
  },
  {
    kanji: "一",
    romaji: [
      { type: "on'yomi", value: "ichi" },
      { type: "kun'yomi", value: "hito" },
    ],
    english: ["one"],
  },
  {
    kanji: "人",
    romaji: [
      { type: "on'yomi", value: "jin" },
      { type: "on'yomi", value: "nin" },
      { type: "kun'yomi", value: "hito" },
    ],
    english: ["person", "human"],
  },
  {
    kanji: "年",
    romaji: [
      { type: "on'yomi", value: "nen" },
      { type: "kun'yomi", value: "toshi" },
    ],
    english: ["year"],
  },
  {
    kanji: "大",
    romaji: [
      { type: "on'yomi", value: "dai" },
      { type: "on'yomi", value: "tai" },
      { type: "kun'yomi", value: "oo" },
    ],
    english: ["big", "large"],
  },
  {
    kanji: "十",
    romaji: [
      { type: "on'yomi", value: "juu" },
      { type: "kun'yomi", value: "tou" },
    ],
    english: ["ten"],
  },
  {
    kanji: "二",
    romaji: [
      { type: "on'yomi", value: "ni" },
      { type: "kun'yomi", value: "futa" },
    ],
    english: ["two"],
  },
  {
    kanji: "本",
    romaji: [
      { type: "on'yomi", value: "hon" },
      { type: "kun'yomi", value: "moto" },
    ],
    english: ["book", "origin", "counter for long objects"],
  },
  {
    kanji: "中",
    romaji: [
      { type: "on'yomi", value: "chuu" },
      { type: "kun'yomi", value: "naka" },
    ],
    english: ["middle", "inside"],
  },
  {
    kanji: "長",
    romaji: [
      { type: "on'yomi", value: "chou" },
      { type: "kun'yomi", value: "naga" },
    ],
    english: ["long", "leader"],
  },
  {
    kanji: "出",
    romaji: [
      { type: "on'yomi", value: "shutsu" },
      { type: "kun'yomi", value: "de" },
      { type: "kun'yomi", value: "da" },
    ],
    english: ["exit", "go out"],
  },
  {
    kanji: "三",
    romaji: [
      { type: "on'yomi", value: "san" },
      { type: "kun'yomi", value: "mi" },
    ],
    english: ["three"],
  },
  {
    kanji: "時",
    romaji: [
      { type: "on'yomi", value: "ji" },
      { type: "kun'yomi", value: "toki" },
    ],
    english: ["time", "hour"],
  },
  {
    kanji: "行",
    romaji: [
      { type: "on'yomi", value: "kou" },
      { type: "on'yomi", value: "gyou" },
      { type: "kun'yomi", value: "i" },
      { type: "kun'yomi", value: "okona" },
    ],
    english: ["go", "conduct", "line"],
  },
  {
    kanji: "見",
    romaji: [
      { type: "on'yomi", value: "ken" },
      { type: "kun'yomi", value: "mi" },
    ],
    english: ["see", "look"],
  },
  {
    kanji: "月",
    romaji: [
      { type: "on'yomi", value: "getsu" },
      { type: "on'yomi", value: "gatsu" },
      { type: "kun'yomi", value: "tsuki" },
    ],
    english: ["month", "moon"],
  },
  {
    kanji: "分",
    romaji: [
      { type: "on'yomi", value: "bun" },
      { type: "on'yomi", value: "fun" },
      { type: "kun'yomi", value: "wa" },
    ],
    english: ["minute", "part", "understand"],
  },
  {
    kanji: "後",
    romaji: [
      { type: "on'yomi", value: "go" },
      { type: "on'yomi", value: "kou" },
      { type: "kun'yomi", value: "ato" },
    ],
    english: ["after", "behind"],
  },
  {
    kanji: "前",
    romaji: [
      { type: "on'yomi", value: "zen" },
      { type: "kun'yomi", value: "mae" },
    ],
    english: ["before", "front"],
  },
  {
    kanji: "生",
    romaji: [
      { type: "on'yomi", value: "sei" },
      { type: "on'yomi", value: "shou" },
      { type: "kun'yomi", value: "i" },
      { type: "kun'yomi", value: "u" },
    ],
    english: ["life", "birth", "live"],
  },
  {
    kanji: "五",
    romaji: [{ type: "on'yomi", value: "go" }],
    english: ["five"],
  },
  {
    kanji: "間",
    romaji: [
      { type: "on'yomi", value: "kan" },
      { type: "on'yomi", value: "ken" },
      { type: "kun'yomi", value: "aida" },
    ],
    english: ["interval", "space", "between"],
  },
  {
    kanji: "上",
    romaji: [
      { type: "on'yomi", value: "jou" },
      { type: "kun'yomi", value: "ue" },
    ],
    english: ["above", "up"],
  },
  {
    kanji: "東",
    romaji: [
      { type: "on'yomi", value: "tou" },
      { type: "kun'yomi", value: "higashi" },
    ],
    english: ["east"],
  },
  {
    kanji: "四",
    romaji: [
      { type: "on'yomi", value: "shi" },
      { type: "kun'yomi", value: "yon" },
    ],
    english: ["four"],
  },
  {
    kanji: "今",
    romaji: [
      { type: "on'yomi", value: "kon" },
      { type: "on'yomi", value: "kin" },
      { type: "kun'yomi", value: "ima" },
    ],
    english: ["now"],
  },
  {
    kanji: "金",
    romaji: [
      { type: "on'yomi", value: "kin" },
      { type: "kun'yomi", value: "kane" },
    ],
    english: ["gold", "money"],
  },
  {
    kanji: "九",
    romaji: [
      { type: "on'yomi", value: "kyuu" },
      { type: "on'yomi", value: "ku" },
    ],
    english: ["nine"],
  },
  {
    kanji: "入",
    romaji: [
      { type: "on'yomi", value: "nyuu" },
      { type: "kun'yomi", value: "i" },
    ],
    english: ["enter"],
  },
  {
    kanji: "学",
    romaji: [
      { type: "on'yomi", value: "gaku" },
      { type: "kun'yomi", value: "mana" },
    ],
    english: ["study", "learning"],
  },
  {
    kanji: "高",
    romaji: [
      { type: "on'yomi", value: "kou" },
      { type: "kun'yomi", value: "taka" },
    ],
    english: ["high", "tall"],
  },
  {
    kanji: "円",
    romaji: [{ type: "on'yomi", value: "en" }],
    english: ["yen", "circle"],
  },
  {
    kanji: "子",
    romaji: [
      { type: "on'yomi", value: "shi" },
      { type: "on'yomi", value: "su" },
      { type: "kun'yomi", value: "ko" },
    ],
    english: ["child", "offspring"],
  },
  {
    kanji: "外",
    romaji: [
      { type: "on'yomi", value: "gai" },
      { type: "kun'yomi", value: "soto" },
    ],
    english: ["outside", "foreign"],
  },
  {
    kanji: "八",
    romaji: [
      { type: "on'yomi", value: "hachi" },
      { type: "kun'yomi", value: "ya" },
    ],
    english: ["eight"],
  },
  {
    kanji: "六",
    romaji: [{ type: "on'yomi", value: "roku" }],
    english: ["six"],
  },
  {
    kanji: "下",
    romaji: [
      { type: "on'yomi", value: "ka" },
      { type: "on'yomi", value: "ge" },
      { type: "kun'yomi", value: "shita" },
    ],
    english: ["below", "down"],
  },
  {
    kanji: "来",
    romaji: [
      { type: "on'yomi", value: "rai" },
      { type: "kun'yomi", value: "ki" },
    ],
    english: ["come"],
  },
  {
    kanji: "気",
    romaji: [
      { type: "on'yomi", value: "ki" },
      { type: "kun'yomi", value: "ke" },
    ],
    english: ["spirit", "mood", "air"],
  },
  {
    kanji: "小",
    romaji: [
      { type: "on'yomi", value: "shou" },
      { type: "kun'yomi", value: "chii" },
      { type: "kun'yomi", value: "ko" },
    ],
    english: ["small", "little"],
  },
  {
    kanji: "七",
    romaji: [
      { type: "on'yomi", value: "shichi" },
      { type: "kun'yomi", value: "nana" },
    ],
    english: ["seven"],
  },
  {
    kanji: "山",
    romaji: [
      { type: "on'yomi", value: "san" },
      { type: "kun'yomi", value: "yama" },
    ],
    english: ["mountain"],
  },
  {
    kanji: "話",
    romaji: [
      { type: "on'yomi", value: "wa" },
      { type: "kun'yomi", value: "hanashi" },
    ],
    english: ["talk", "story"],
  },
  {
    kanji: "女",
    romaji: [
      { type: "on'yomi", value: "jo" },
      { type: "on'yomi", value: "nyo" },
      { type: "kun'yomi", value: "onna" },
    ],
    english: ["woman", "female"],
  },
  {
    kanji: "北",
    romaji: [
      { type: "on'yomi", value: "hoku" },
      { type: "kun'yomi", value: "kita" },
    ],
    english: ["north"],
  },
  {
    kanji: "午",
    romaji: [{ type: "on'yomi", value: "go" }],
    english: ["noon"],
  },
  {
    kanji: "百",
    romaji: [{ type: "on'yomi", value: "hyaku" }],
    english: ["hundred"],
  },
  {
    kanji: "書",
    romaji: [
      { type: "on'yomi", value: "sho" },
      { type: "kun'yomi", value: "ka" },
    ],
    english: ["write"],
  },
  {
    kanji: "先",
    romaji: [
      { type: "on'yomi", value: "sen" },
      { type: "kun'yomi", value: "saki" },
    ],
    english: ["previous", "ahead"],
  },
  {
    kanji: "名",
    romaji: [
      { type: "on'yomi", value: "mei" },
      { type: "on'yomi", value: "myou" },
      { type: "kun'yomi", value: "na" },
    ],
    english: ["name", "famous"],
  },
  {
    kanji: "川",
    romaji: [
      { type: "on'yomi", value: "sen" },
      { type: "kun'yomi", value: "kawa" },
    ],
    english: ["river"],
  },
  {
    kanji: "千",
    romaji: [
      { type: "on'yomi", value: "sen" },
      { type: "kun'yomi", value: "chi" },
    ],
    english: ["thousand"],
  },
  {
    kanji: "水",
    romaji: [
      { type: "on'yomi", value: "sui" },
      { type: "kun'yomi", value: "mizu" },
    ],
    english: ["water"],
  },
  {
    kanji: "半",
    romaji: [{ type: "on'yomi", value: "han" }],
    english: ["half"],
  },
  {
    kanji: "男",
    romaji: [
      { type: "on'yomi", value: "dan" },
      { type: "on'yomi", value: "nan" },
      { type: "kun'yomi", value: "otoko" },
    ],
    english: ["man", "male"],
  },
  {
    kanji: "西",
    romaji: [
      { type: "on'yomi", value: "sei" },
      { type: "kun'yomi", value: "nishi" },
    ],
    english: ["west"],
  },
  {
    kanji: "電",
    romaji: [{ type: "on'yomi", value: "den" }],
    english: ["electricity"],
  },
  {
    kanji: "校",
    romaji: [{ type: "on'yomi", value: "kou" }],
    english: ["school"],
  },
  {
    kanji: "語",
    romaji: [
      { type: "on'yomi", value: "go" },
      { type: "kun'yomi", value: "kata" },
    ],
    english: ["language", "word"],
  },
  {
    kanji: "土",
    romaji: [
      { type: "on'yomi", value: "do" },
      { type: "on'yomi", value: "to" },
      { type: "kun'yomi", value: "tsuchi" },
    ],
    english: ["earth", "soil"],
  },
  {
    kanji: "木",
    romaji: [
      { type: "on'yomi", value: "moku" },
      { type: "kun'yomi", value: "ki" },
    ],
    english: ["tree", "wood"],
  },
  {
    kanji: "聞",
    romaji: [
      { type: "on'yomi", value: "bun" },
      { type: "on'yomi", value: "mon" },
      { type: "kun'yomi", value: "ki" },
    ],
    english: ["hear", "listen"],
  },
  {
    kanji: "食",
    romaji: [
      { type: "on'yomi", value: "shoku" },
      { type: "kun'yomi", value: "ta" },
    ],
    english: ["eat", "food"],
  },
  {
    kanji: "車",
    romaji: [
      { type: "on'yomi", value: "sha" },
      { type: "kun'yomi", value: "kuruma" },
    ],
    english: ["car", "vehicle"],
  },
  {
    kanji: "何",
    romaji: [
      { type: "on'yomi", value: "ka" },
      { type: "kun'yomi", value: "nani" },
    ],
    english: ["what"],
  },
  {
    kanji: "南",
    romaji: [
      { type: "on'yomi", value: "nan" },
      { type: "kun'yomi", value: "minami" },
    ],
    english: ["south"],
  },
  {
    kanji: "万",
    romaji: [
      { type: "on'yomi", value: "man" },
      { type: "on'yomi", value: "ban" },
    ],
    english: ["ten thousand"],
  },
  {
    kanji: "毎",
    romaji: [{ type: "on'yomi", value: "mai" }],
    english: ["every"],
  },
  {
    kanji: "白",
    romaji: [
      { type: "on'yomi", value: "haku" },
      { type: "kun'yomi", value: "shiro" },
    ],
    english: ["white"],
  },
  {
    kanji: "天",
    romaji: [{ type: "on'yomi", value: "ten" }],
    english: ["heaven", "sky"],
  },
  {
    kanji: "母",
    romaji: [
      { type: "on'yomi", value: "bo" },
      { type: "kun'yomi", value: "haha" },
    ],
    english: ["mother"],
  },
  {
    kanji: "火",
    romaji: [
      { type: "on'yomi", value: "ka" },
      { type: "kun'yomi", value: "hi" },
    ],
    english: ["fire"],
  },
  {
    kanji: "右",
    romaji: [
      { type: "on'yomi", value: "u" },
      { type: "kun'yomi", value: "migi" },
    ],
    english: ["right"],
  },
  {
    kanji: "読",
    romaji: [
      { type: "on'yomi", value: "doku" },
      { type: "kun'yomi", value: "yo" },
    ],
    english: ["read"],
  },
  {
    kanji: "友",
    romaji: [
      { type: "on'yomi", value: "yuu" },
      { type: "kun'yomi", value: "tomo" },
    ],
    english: ["friend"],
  },
  {
    kanji: "左",
    romaji: [
      { type: "on'yomi", value: "sa" },
      { type: "kun'yomi", value: "hidari" },
    ],
    english: ["left"],
  },
  {
    kanji: "休",
    romaji: [
      { type: "on'yomi", value: "kyuu" },
      { type: "kun'yomi", value: "yasu" },
    ],
    english: ["rest"],
  },
  {
    kanji: "父",
    romaji: [
      { type: "on'yomi", value: "fu" },
      { type: "kun'yomi", value: "tou" },
    ],
    english: ["father"],
  },
  {
    kanji: "会",
    romaji: [
      { type: "on'yomi", value: "kai" },
      { type: "kun'yomi", value: "a" },
    ],
    english: ["meet", "meeting"],
  },
  {
    kanji: "買",
    romaji: [
      { type: "on'yomi", value: "bai" },
      { type: "kun'yomi", value: "ka" },
    ],
    english: ["buy"],
  },
  {
    kanji: "田",
    romaji: [
      { type: "on'yomi", value: "den" },
      { type: "kun'yomi", value: "ta" },
    ],
    english: ["rice field"],
  },
  {
    kanji: "雨",
    romaji: [
      { type: "on'yomi", value: "u" },
      { type: "kun'yomi", value: "ame" },
    ],
    english: ["rain"],
  },
  {
    kanji: "駅",
    romaji: [{ type: "on'yomi", value: "eki" }],
    english: ["station"],
  },
  {
    kanji: "春",
    romaji: [
      { type: "on'yomi", value: "shun" },
      { type: "kun'yomi", value: "haru" },
    ],
    english: ["spring"],
  },
  {
    kanji: "秋",
    romaji: [
      { type: "on'yomi", value: "shuu" },
      { type: "kun'yomi", value: "aki" },
    ],
    english: ["autumn"],
  },
  {
    kanji: "夏",
    romaji: [
      { type: "on'yomi", value: "ka" },
      { type: "kun'yomi", value: "natsu" },
    ],
    english: ["summer"],
  },
  {
    kanji: "冬",
    romaji: [
      { type: "on'yomi", value: "tou" },
      { type: "kun'yomi", value: "fuyu" },
    ],
    english: ["winter"],
  },
  {
    kanji: "朝",
    romaji: [
      { type: "on'yomi", value: "chou" },
      { type: "kun'yomi", value: "asa" },
    ],
    english: ["morning"],
  },
  {
    kanji: "昼",
    romaji: [
      { type: "on'yomi", value: "chuu" },
      { type: "kun'yomi", value: "hiru" },
    ],
    english: ["noon", "daytime"],
  },
  {
    kanji: "夜",
    romaji: [
      { type: "on'yomi", value: "ya" },
      { type: "kun'yomi", value: "yoru" },
    ],
    english: ["night"],
  },
  {
    kanji: "週",
    romaji: [{ type: "on'yomi", value: "shuu" }],
    english: ["week"],
  },
  {
    kanji: "道",
    romaji: [
      { type: "on'yomi", value: "dou" },
      { type: "kun'yomi", value: "michi" },
    ],
    english: ["road", "way"],
  },
  {
    kanji: "新",
    romaji: [
      { type: "on'yomi", value: "shin" },
      { type: "kun'yomi", value: "ara" },
    ],
    english: ["new"],
  },
  {
    kanji: "古",
    romaji: [
      { type: "on'yomi", value: "ko" },
      { type: "kun'yomi", value: "furu" },
    ],
    english: ["old"],
  },
  {
    kanji: "海",
    romaji: [
      { type: "on'yomi", value: "kai" },
      { type: "kun'yomi", value: "umi" },
    ],
    english: ["sea"],
  },
  {
    kanji: "花",
    romaji: [
      { type: "on'yomi", value: "ka" },
      { type: "kun'yomi", value: "hana" },
    ],
    english: ["flower"],
  },
  {
    kanji: "空",
    romaji: [
      { type: "on'yomi", value: "kuu" },
      { type: "kun'yomi", value: "sora" },
    ],
    english: ["sky", "empty"],
  },
  {
    kanji: "犬",
    romaji: [
      { type: "on'yomi", value: "ken" },
      { type: "kun'yomi", value: "inu" },
    ],
    english: ["dog"],
  },
  {
    kanji: "猫",
    romaji: [
      { type: "on'yomi", value: "byou" },
      { type: "kun'yomi", value: "neko" },
    ],
    english: ["cat"],
  },
];

export default kanji;
